
  const Product = [
    {
      id: 1,
      name: "Obstacle Avoiding Robot",
      price: "₹999",
      description: "a robot which avoids whatever comes in its path and changes its direction automatically",
      image: "/Content_Image_1.jpeg",
    },
    {
      id: 2,
      name: "Arduino Car",
      price: "₹999",
      description: "Its a bluetooth controlled car using arduino which can be controlled using mobile." ,
      image: "/image2.jpeg",
    },
    {
      id: 3,
      name: "Wireless Charger",
      price: "₹699",
      description: "DIY wireless charger circuit",
      image: "/image3.jpeg",
    },
    {
      id: 4,
      name: "Line Follower Robot",
      price: "₹1199",
      description: "Smart robot that follows a line path",
      image: "/image4.jpeg",
    },
    {
      id: 5,
      name: "Voice Controlled Switch",
      price: "₹899",
      description: "Home automation using voice commands",
      image: "/image5.jpeg",
    },
    {
      id: 6,
      name: "Smart Door Lock",
      price: "₹1299",
      description: "IoT-based digital door lock system",
      image: "/image6.jpg",
    },
    {
      id: 7,
      name: "Solar Power Bank",
      price: "₹1499",
      description: "DIY solar-powered power bank",
      image: "solarpowerbank.jpg",
    },
    {
      id: 8,
      name: "Gesture Controlled Car",
      price: "₹1599",
      description: "Arduino based gesture control project",
      image: "gesturecar.png",
    },
    {
      id:9,
      name: "Smart Irrigation System",
      price: "₹1999",
      description: "Automated irrigation using soil moisture sensors",
      image: "irrigationsystem.jpg",
    },
    {
      id:10,
      name: "RFID Based Access Control",
      price: "₹1199",
      description: "Secure access using RFID technology",
      image: "RFIDbasedaccesscontrol.jpg",
    },
    {
      id:11,
      name: "DHT11 Humidity and Temperature Sensor",
      price: "₹499",
      description: "Measure humidity and temperature with DHT11 sensor",
      image: "temperature.jpg",
    },
    {
      id:12,
      name: "Automatic Plant Watering System",
      price: "₹899",
      description: "Keep your plants hydrated automatically",
      image: "Automaticwateringsystem.jpg",
    },
    {
      id:13,
      name: "Motion Detector Alarm",
      price: "₹799",
      description: "Detects motion and triggers an alarm",
      image: "motiondetectionalarm.jpg",
    }
  ];
export default Product;